'use client';
import React, { useEffect, useState } from 'react';
import { OfficialLogo } from '@/components/OfficialLogo';
import { getSupabaseClient } from '@/lib/supabaseClient';
import { checkPassword, PASSWORD_MIN } from '@/lib/password';
import { validateFirstAccessPasswords } from '@/lib/firstAccess';

type Profile = { name?:string; email?:string; full_name?:string; phone?:string; cpf?:string; birth_date?:string; status?:string; first_access_completed?:boolean };
export default function PrimeiroAcessoPage() {
  const [profile,setProfile]=useState<Profile|null>(null), [invalid,setInvalid]=useState(false), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false);
  const [fullName,setFullName]=useState(''),[phone,setPhone]=useState(''),[cpf,setCpf]=useState(''),[birth,setBirth]=useState('');
  const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[error,setError]=useState('');
  useEffect(()=>{ let active=true; (async()=>{try{const s=getSupabaseClient() as any; const code=new URLSearchParams(location.search).get('code'); if(code) await s.auth.exchangeCodeForSession(code); const {data}=await s.auth.getSession(); if(!data.session?.user) throw new Error(); const {data:p,error:e}=await s.from('profiles').select('name,email,full_name,phone,cpf,birth_date,status,first_access_completed').eq('id',data.session.user.id).single(); if(e||!p||p.status!=='ATIVO'||p.first_access_completed) throw new Error(); if(active){setProfile(p);setFullName(p.full_name||p.name||'');setPhone(p.phone||'');setCpf(p.cpf||'');setBirth(p.birth_date||'');}}catch{if(active)setInvalid(true);}finally{if(active)setLoading(false);}})(); return()=>{active=false};},[]);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();const msg=validateFirstAccessPasswords(password,confirm);if(msg){setError(msg);return;}setSaving(true);setError('');try{const s=getSupabaseClient() as any;const {error:pw}=await s.auth.updateUser({password});if(pw)throw pw;const {error:rpc}=await s.rpc('complete_employee_first_access',{p_full_name:fullName||null,p_phone:phone||null,p_cpf:cpf||null,p_birth_date:birth||null});if(rpc)throw rpc;location.replace('/funcionarios/');}catch{setError('Não foi possível concluir o cadastro. Verifique o link ou tente novamente.');}finally{setSaving(false);}};
  const checks=checkPassword(password);
  return <main className="min-h-[100dvh] bg-[#1A1A72] px-4 flex items-center justify-center" style={{paddingTop:'max(1rem, env(safe-area-inset-top))',paddingBottom:'max(1rem, env(safe-area-inset-bottom))'}}><div className="w-full max-w-md bg-[#f8f9ff] rounded-2xl p-5 sm:p-7 shadow-2xl border border-white/30">
    <div className="text-center mb-5"><OfficialLogo className="w-16 h-16 mx-auto mb-2"/><h1 className="text-2xl font-bold text-[#1A1A72]">Bem-vindo à Fireowl</h1><p className="text-sm text-slate-600 mt-1">Complete seu cadastro para acessar o Fireowl Guardian.</p></div>
    {loading?<p className="text-center text-sm text-slate-500">Validando convite...</p>:invalid?<div role="alert" className="text-center rounded-xl bg-red-50 border border-red-200 p-5"><p className="font-bold text-[#E63946]">Este convite expirou ou não é mais válido.</p><p className="text-sm text-slate-600 mt-2">Solicite um novo convite ao administrador.</p></div>:<form onSubmit={submit} className="space-y-3">
      <label className="block text-xs font-semibold text-slate-600">Nome completo<input className="mt-1 w-full min-h-11 rounded-lg border border-slate-300 px-3" value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" required/></label>
      <label className="block text-xs font-semibold text-slate-600">E-mail<input className="mt-1 w-full min-h-11 rounded-lg border border-slate-200 bg-slate-100 px-3 text-slate-500" value={profile?.email||''} disabled/></label>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Telefone<input className="mt-1 w-full min-h-11 rounded-lg border border-slate-300 px-3" value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" autoComplete="tel"/></label><label className="text-xs font-semibold text-slate-600">CPF<input className="mt-1 w-full min-h-11 rounded-lg border border-slate-300 px-3" value={cpf} onChange={e=>setCpf(e.target.value)} inputMode="numeric"/></label></div>
      <label className="block text-xs font-semibold text-slate-600">Data de nascimento<input type="date" className="mt-1 w-full min-h-11 rounded-lg border border-slate-300 px-3" value={birth} onChange={e=>setBirth(e.target.value)} autoComplete="bday"/></label>
      <label className="block text-xs font-semibold text-slate-600">Nova senha<div className="relative mt-1"><input type={show?'text':'password'} className="w-full min-h-11 rounded-lg border border-slate-300 px-3 pr-12" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password" required/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-1 top-1 min-w-10 min-h-9" aria-label={show?'Ocultar senha':'Mostrar senha'}>{show?'🙈':'👁'}</button></div></label>
      <label className="block text-xs font-semibold text-slate-600">Confirmar nova senha<input type={show?'text':'password'} className="mt-1 w-full min-h-11 rounded-lg border border-slate-300 px-3" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></label>
      <ul className="grid grid-cols-2 gap-x-2 text-[11px] text-slate-600" aria-label="Requisitos da senha"><li>{checks.length?'✓':'○'} {PASSWORD_MIN}+ caracteres</li><li>{checks.upper?'✓':'○'} Maiúscula</li><li>{checks.lower?'✓':'○'} Minúscula</li><li>{checks.digit?'✓':'○'} Número</li><li>{checks.symbol?'✓':'○'} Símbolo</li></ul>
      {error&&<p role="alert" className="text-xs font-semibold text-[#E63946]">{error}</p>}<button disabled={saving} className="w-full min-h-[52px] rounded-lg bg-[#E63946] text-white font-bold uppercase tracking-wider disabled:opacity-60">{saving?'Concluindo...':'Concluir cadastro'}</button>
    </form>}
  </div></main>;
}
