'use client';
import React, { useEffect, useState } from 'react';
import { AuthUser, getSessionUser } from '@/lib/auth';
import { validateFirstAccessPasswords } from '@/lib/firstAccess';
import { checkPassword, PASSWORD_MIN } from '@/lib/password';
import { getSupabaseClient } from '@/lib/supabaseClient';
import { OfficialLogo } from '@/components/OfficialLogo';

export function FirstAccessRequired({ user, onCompleted }: { user: AuthUser; onCompleted?: (user: AuthUser) => void }) {
  const [password, setPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false), [error, setError] = useState('');
  const [profileFields, setProfileFields] = useState<Record<string, string | null>>({});
  const checks = checkPassword(password);
  useEffect(() => { let active = true; const s = getSupabaseClient() as any; s.from('profiles').select('full_name,phone,cpf,birth_date').eq('id', user.id).single().then(({ data }: any) => { if (active && data) setProfileFields(data); }).catch(() => {}); return () => { active = false; }; }, [user.id]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const validation = validateFirstAccessPasswords(password, confirmation); if (validation) { setError(validation); return; } setSaving(true); setError(''); try { const s = getSupabaseClient() as any; const { error: passwordError } = await s.auth.updateUser({ password }); if (passwordError) throw passwordError; const { error: completeError } = await s.rpc('complete_employee_first_access', { p_full_name: profileFields.full_name ?? user.name, p_phone: profileFields.phone ?? null, p_cpf: profileFields.cpf ?? null, p_birth_date: profileFields.birth_date ?? null }); if (completeError) throw completeError; const refreshed = await getSessionUser(); if (!refreshed?.firstAccessCompleted) throw new Error('FIRST_ACCESS_NOT_COMPLETED'); if (onCompleted) onCompleted(refreshed); else window.location.replace('/funcionarios/'); } catch { setError('Não foi possível alterar a senha. Tente novamente.'); } finally { setSaving(false); } };
  return <main className="min-h-[100dvh] bg-[#1A1A72] px-4 flex items-center justify-center" style={{ paddingTop: 'max(1rem, env(safe-area-inset-top))', paddingBottom: 'max(1rem, env(safe-area-inset-bottom))' }}><div className="w-full max-w-md rounded-2xl border border-white/30 bg-[#f8f9ff] p-5 shadow-2xl sm:p-7"><div className="mb-5 text-center"><OfficialLogo className="mx-auto mb-2 h-16 w-16"/><h1 className="text-2xl font-bold text-[#1A1A72]">Crie sua nova senha</h1><p className="mt-2 text-sm text-slate-600">Por segurança, você precisa alterar a senha temporária antes de acessar o Fireowl Guardian.</p></div><div className="mb-4 rounded-xl bg-indigo-50 p-3 text-sm"><p className="font-bold text-slate-900">{user.name}</p><p className="font-data-mono text-xs text-slate-600">{user.email}</p></div><form onSubmit={submit} className="space-y-3"><label className="block text-xs font-semibold text-slate-600">Nova senha<div className="relative mt-1"><input type={show ? 'text' : 'password'} className="min-h-11 w-full rounded-lg border border-slate-300 px-3 pr-12" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="new-password" required/><button type="button" onClick={() => setShow((v) => !v)} className="absolute right-1 top-1 min-h-9 min-w-10" aria-label={show ? 'Ocultar senha' : 'Mostrar senha'}><span className="material-symbols-outlined">{show ? 'visibility_off' : 'visibility'}</span></button></div></label><label className="block text-xs font-semibold text-slate-600">Confirmar nova senha<input type={show ? 'text' : 'password'} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 px-3" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} autoComplete="new-password" required/></label><ul className="grid grid-cols-2 gap-x-2 text-[11px] text-slate-600"><li>{checks.length ? '✓' : '○'} {PASSWORD_MIN}+ caracteres</li><li>{checks.upper ? '✓' : '○'} Maiúscula</li><li>{checks.lower ? '✓' : '○'} Minúscula</li><li>{checks.digit ? '✓' : '○'} Número</li><li>{checks.symbol ? '✓' : '○'} Símbolo</li></ul>{error && <p role="alert" className="text-xs font-semibold text-[#E63946]">{error}</p>}<button disabled={saving} className="min-h-[52px] w-full rounded-lg bg-[#E63946] font-bold uppercase tracking-wider text-white disabled:opacity-60">{saving ? 'Alterando...' : 'Alterar senha e continuar'}</button></form></div></main>;
}
